
~/Informatique/S3/bin/tri_tableau: tri_tableau.c
	gcc -I ~/Informatique/S3/include -ggdb3 -Wall -Werror -Wextra tri_tableau.c -o  ~/Informatique/S3/bin/tri_tableau


run/tri_tableau.c: ~/Informatique/S3/bin/tri_tableau
	~/Informatique/S3/bin/tri_tableau
